x-tts-server-base: &tts-server-base
  build:
    context: https://github.com/idiap/coqui-ai-TTS.git
    dockerfile: Dockerfile

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  tts-server-cpu:
    <<: *tts-server-base
    container_name: coqui-tts-cpu
    entrypoint: 'python3 TTS/server/server.py --model_name tts_models/cs/cv/vits --port 5002'
    ports:
      - '5002:5002'

  tts-server-gpu:
    <<: *tts-server-base
    container_name: coqui-tts-gpu
    entrypoint: 'python3 TTS/server/server.py --model_name tts_models/cs/cv/vits --port 5003 --use_cuda'
    ports:
      - '5003:5003'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']
              count: 1

volumes:
  redis_data:
